---

- name: add apt https support
  apt:
    cache_valid_time: 3600
    update_cache: yes
    pkg:
      - apt-transport-https
      - gnupg
      - cron
      - ca-certificates
  when: ansible_distribution_major_version < 11

- name: add docker gpg key to apt keyring
  apt_key:
    id: 2472D6D0D2F66AF87ABA8DA34D64390375060AA4
    url: https://ftp.uni-stuttgart.de/opensuse/repositories/devel:/kubic:/libcontainers:/stable/{{ obs_distro }}/Release.key
  when: ansible_distribution_major_version < 11

- apt_repository:
    repo: "deb https://ftp.uni-stuttgart.de/opensuse/repositories/devel:/kubic:/libcontainers:/stable/{{ obs_distro }}/ /"
    state: present
    update_cache: yes
  when: ansible_distribution_major_version < 11

- name: install podman
  apt:
    pkg:
      - podman
      - runc
      - buildah
      - skopeo
      - dnsmasq
